// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CC.Login.proto

package im.jizhu.com.loginmodule.protobuf;

public final class CCLogin {
  private CCLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CCHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CC.Login.CCHeartBeat)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code CC.Login.CCHeartBeat}
   */
  public static final class CCHeartBeat extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:CC.Login.CCHeartBeat)
      CCHeartBeatOrBuilder {
    // Use CCHeartBeat.newBuilder() to construct.
    private CCHeartBeat(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CCHeartBeat(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final CCHeartBeat defaultInstance;
    public static CCHeartBeat getDefaultInstance() {
      return defaultInstance;
    }

    public CCHeartBeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private CCHeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<CCHeartBeat> PARSER =
        new com.google.protobuf.AbstractParser<CCHeartBeat>() {
      public CCHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CCHeartBeat(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CCHeartBeat> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code CC.Login.CCHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CC.Login.CCHeartBeat)
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeatOrBuilder {
      // Construct using im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat getDefaultInstanceForType() {
        return im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat.getDefaultInstance();
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat build() {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat buildPartial() {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat result = new im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat(this);
        return result;
      }

      public Builder mergeFrom(im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat other) {
        if (other == im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat.getDefaultInstance()) return this;
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (im.jizhu.com.loginmodule.protobuf.CCLogin.CCHeartBeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CC.Login.CCHeartBeat)
    }

    static {
      defaultInstance = new CCHeartBeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CC.Login.CCHeartBeat)
  }

  public interface CCLoginReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CC.Login.CCLoginReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *登陆账号	
     * </pre>
     */
    boolean hasAccount();
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *登陆账号	
     * </pre>
     */
    String getAccount();
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *登陆账号	
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    String getPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
     *
     * <pre>
     *设备信息	
     * </pre>
     */
    boolean hasDeviceinfo();
    /**
     * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
     *
     * <pre>
     *设备信息	
     * </pre>
     */
    im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo getDeviceinfo();

    /**
     * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
     *
     * <pre>
     *网络信息
     * </pre>
     */
    boolean hasIpinfo();
    /**
     * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
     *
     * <pre>
     *网络信息
     * </pre>
     */
    im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo getIpinfo();

    /**
     * <code>required uint32 tenant_id = 5 [default = 0];</code>
     *
     * <pre>
     *租户ID
     * </pre>
     */
    boolean hasTenantId();
    /**
     * <code>required uint32 tenant_id = 5 [default = 0];</code>
     *
     * <pre>
     *租户ID
     * </pre>
     */
    int getTenantId();

    /**
     * <code>required string version = 6;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required string version = 6;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    String getVersion();
    /**
     * <code>required string version = 6;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code CC.Login.CCLoginReq}
   */
  public static final class CCLoginReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:CC.Login.CCLoginReq)
      CCLoginReqOrBuilder {
    // Use CCLoginReq.newBuilder() to construct.
    private CCLoginReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CCLoginReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final CCLoginReq defaultInstance;
    public static CCLoginReq getDefaultInstance() {
      return defaultInstance;
    }

    public CCLoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private CCLoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              account_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
            case 26: {
              im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = deviceinfo_.toBuilder();
              }
              deviceinfo_ = input.readMessage(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deviceinfo_);
                deviceinfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = ipinfo_.toBuilder();
              }
              ipinfo_ = input.readMessage(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ipinfo_);
                ipinfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              tenantId_ = input.readUInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              version_ = bs;
              break;
            }
            case 162: {
              bitField0_ |= 0x00000040;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<CCLoginReq> PARSER =
        new com.google.protobuf.AbstractParser<CCLoginReq>() {
      public CCLoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CCLoginReq(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CCLoginReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private Object account_;
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *登陆账号	
     * </pre>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *登陆账号	
     * </pre>
     */
    public String getAccount() {
      Object ref = account_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *登陆账号	
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private Object password_;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEINFO_FIELD_NUMBER = 3;
    private im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo deviceinfo_;
    /**
     * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
     *
     * <pre>
     *设备信息	
     * </pre>
     */
    public boolean hasDeviceinfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
     *
     * <pre>
     *设备信息	
     * </pre>
     */
    public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo getDeviceinfo() {
      return deviceinfo_;
    }

    public static final int IPINFO_FIELD_NUMBER = 4;
    private im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo ipinfo_;
    /**
     * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
     *
     * <pre>
     *网络信息
     * </pre>
     */
    public boolean hasIpinfo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
     *
     * <pre>
     *网络信息
     * </pre>
     */
    public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo getIpinfo() {
      return ipinfo_;
    }

    public static final int TENANT_ID_FIELD_NUMBER = 5;
    private int tenantId_;
    /**
     * <code>required uint32 tenant_id = 5 [default = 0];</code>
     *
     * <pre>
     *租户ID
     * </pre>
     */
    public boolean hasTenantId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 tenant_id = 5 [default = 0];</code>
     *
     * <pre>
     *租户ID
     * </pre>
     */
    public int getTenantId() {
      return tenantId_;
    }

    public static final int VERSION_FIELD_NUMBER = 6;
    private Object version_;
    /**
     * <code>required string version = 6;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string version = 6;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string version = 6;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      account_ = "";
      password_ = "";
      deviceinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.getDefaultInstance();
      ipinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.getDefaultInstance();
      tenantId_ = 0;
      version_ = "";
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTenantId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, deviceinfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, ipinfo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, tenantId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getVersionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, deviceinfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, ipinfo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, tenantId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getVersionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code CC.Login.CCLoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CC.Login.CCLoginReq)
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReqOrBuilder {
      // Construct using im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000004);
        ipinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000008);
        tenantId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq getDefaultInstanceForType() {
        return im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq.getDefaultInstance();
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq build() {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq buildPartial() {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq result = new im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceinfo_ = deviceinfo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ipinfo_ = ipinfo_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.tenantId_ = tenantId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq other) {
        if (other == im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          bitField0_ |= 0x00000001;
          account_ = other.account_;
          
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          
        }
        if (other.hasDeviceinfo()) {
          mergeDeviceinfo(other.getDeviceinfo());
        }
        if (other.hasIpinfo()) {
          mergeIpinfo(other.getIpinfo());
        }
        if (other.hasTenantId()) {
          setTenantId(other.getTenantId());
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000020;
          version_ = other.version_;
          
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (!hasTenantId()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object account_ = "";
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *登陆账号	
       * </pre>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *登陆账号	
       * </pre>
       */
      public String getAccount() {
        Object ref = account_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *登陆账号	
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *登陆账号	
       * </pre>
       */
      public Builder setAccount(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        
        return this;
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *登陆账号	
       * </pre>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = getDefaultInstance().getAccount();
        
        return this;
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *登陆账号	
       * </pre>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        
        return this;
      }

      private Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        
        return this;
      }

      private im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo deviceinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.getDefaultInstance();
      /**
       * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
       *
       * <pre>
       *设备信息	
       * </pre>
       */
      public boolean hasDeviceinfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
       *
       * <pre>
       *设备信息	
       * </pre>
       */
      public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo getDeviceinfo() {
        return deviceinfo_;
      }
      /**
       * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
       *
       * <pre>
       *设备信息	
       * </pre>
       */
      public Builder setDeviceinfo(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        deviceinfo_ = value;

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
       *
       * <pre>
       *设备信息	
       * </pre>
       */
      public Builder setDeviceinfo(
          im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.Builder builderForValue) {
        deviceinfo_ = builderForValue.build();

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
       *
       * <pre>
       *设备信息	
       * </pre>
       */
      public Builder mergeDeviceinfo(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo value) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            deviceinfo_ != im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.getDefaultInstance()) {
          deviceinfo_ =
            im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.newBuilder(deviceinfo_).mergeFrom(value).buildPartial();
        } else {
          deviceinfo_ = value;
        }

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.DeviceInfo deviceinfo = 3;</code>
       *
       * <pre>
       *设备信息	
       * </pre>
       */
      public Builder clearDeviceinfo() {
        deviceinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.DeviceInfo.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      private im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo ipinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.getDefaultInstance();
      /**
       * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
       *
       * <pre>
       *网络信息
       * </pre>
       */
      public boolean hasIpinfo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
       *
       * <pre>
       *网络信息
       * </pre>
       */
      public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo getIpinfo() {
        return ipinfo_;
      }
      /**
       * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
       *
       * <pre>
       *网络信息
       * </pre>
       */
      public Builder setIpinfo(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ipinfo_ = value;

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
       *
       * <pre>
       *网络信息
       * </pre>
       */
      public Builder setIpinfo(
          im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.Builder builderForValue) {
        ipinfo_ = builderForValue.build();

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
       *
       * <pre>
       *网络信息
       * </pre>
       */
      public Builder mergeIpinfo(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo value) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            ipinfo_ != im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.getDefaultInstance()) {
          ipinfo_ =
            im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.newBuilder(ipinfo_).mergeFrom(value).buildPartial();
        } else {
          ipinfo_ = value;
        }

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.IPInfo ipinfo = 4;</code>
       *
       * <pre>
       *网络信息
       * </pre>
       */
      public Builder clearIpinfo() {
        ipinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.IPInfo.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      private int tenantId_ ;
      /**
       * <code>required uint32 tenant_id = 5 [default = 0];</code>
       *
       * <pre>
       *租户ID
       * </pre>
       */
      public boolean hasTenantId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 tenant_id = 5 [default = 0];</code>
       *
       * <pre>
       *租户ID
       * </pre>
       */
      public int getTenantId() {
        return tenantId_;
      }
      /**
       * <code>required uint32 tenant_id = 5 [default = 0];</code>
       *
       * <pre>
       *租户ID
       * </pre>
       */
      public Builder setTenantId(int value) {
        bitField0_ |= 0x00000010;
        tenantId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 tenant_id = 5 [default = 0];</code>
       *
       * <pre>
       *租户ID
       * </pre>
       */
      public Builder clearTenantId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tenantId_ = 0;
        
        return this;
      }

      private Object version_ = "";
      /**
       * <code>required string version = 6;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string version = 6;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string version = 6;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string version = 6;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        version_ = value;
        
        return this;
      }
      /**
       * <code>required string version = 6;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        version_ = getDefaultInstance().getVersion();
        
        return this;
      }
      /**
       * <code>required string version = 6;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        version_ = value;
        
        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        attachData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        attachData_ = getDefaultInstance().getAttachData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CC.Login.CCLoginReq)
    }

    static {
      defaultInstance = new CCLoginReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CC.Login.CCLoginReq)
  }

  public interface CCLoginResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CC.Login.CCLoginRes)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .CC.BaseDefine.LoginResultCode result_code = 1;</code>
     *
     * <pre>
     *结果码
     * </pre>
     */
    boolean hasResultCode();
    /**
     * <code>required .CC.BaseDefine.LoginResultCode result_code = 1;</code>
     *
     * <pre>
     *结果码
     * </pre>
     */
    im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode getResultCode();

    /**
     * <code>required string result_msg = 2;</code>
     *
     * <pre>
     *结果提示信息
     * </pre>
     */
    boolean hasResultMsg();
    /**
     * <code>required string result_msg = 2;</code>
     *
     * <pre>
     *结果提示信息
     * </pre>
     */
    String getResultMsg();
    /**
     * <code>required string result_msg = 2;</code>
     *
     * <pre>
     *结果提示信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getResultMsgBytes();

    /**
     * <code>optional string account = 3;</code>
     */
    boolean hasAccount();
    /**
     * <code>optional string account = 3;</code>
     */
    String getAccount();
    /**
     * <code>optional string account = 3;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
     *
     * <pre>
     *用户信息列表
     * </pre>
     */
    boolean hasUserinfo();
    /**
     * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
     *
     * <pre>
     *用户信息列表
     * </pre>
     */
    im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo getUserinfo();

    /**
     * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
     *
     * <pre>
     *帐号信息列表
     * </pre>
     */
    java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo>
        getAccountlistList();
    /**
     * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
     *
     * <pre>
     *帐号信息列表
     * </pre>
     */
    im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo getAccountlist(int index);
    /**
     * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
     *
     * <pre>
     *帐号信息列表
     * </pre>
     */
    int getAccountlistCount();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code CC.Login.CCLoginRes}
   */
  public static final class CCLoginRes extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:CC.Login.CCLoginRes)
      CCLoginResOrBuilder {
    // Use CCLoginRes.newBuilder() to construct.
    private CCLoginRes(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CCLoginRes(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final CCLoginRes defaultInstance;
    public static CCLoginRes getDefaultInstance() {
      return defaultInstance;
    }

    public CCLoginRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private CCLoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode value = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              resultMsg_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              account_ = bs;
              break;
            }
            case 34: {
              im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = userinfo_.toBuilder();
              }
              userinfo_ = input.readMessage(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userinfo_);
                userinfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                accountlist_ = new java.util.ArrayList<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo>();
                mutable_bitField0_ |= 0x00000010;
              }
              accountlist_.add(input.readMessage(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo.PARSER, extensionRegistry));
              break;
            }
            case 162: {
              bitField0_ |= 0x00000010;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          accountlist_ = java.util.Collections.unmodifiableList(accountlist_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<CCLoginRes> PARSER =
        new com.google.protobuf.AbstractParser<CCLoginRes>() {
      public CCLoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CCLoginRes(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CCLoginRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_CODE_FIELD_NUMBER = 1;
    private im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode resultCode_;
    /**
     * <code>required .CC.BaseDefine.LoginResultCode result_code = 1;</code>
     *
     * <pre>
     *结果码
     * </pre>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .CC.BaseDefine.LoginResultCode result_code = 1;</code>
     *
     * <pre>
     *结果码
     * </pre>
     */
    public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode getResultCode() {
      return resultCode_;
    }

    public static final int RESULT_MSG_FIELD_NUMBER = 2;
    private Object resultMsg_;
    /**
     * <code>required string result_msg = 2;</code>
     *
     * <pre>
     *结果提示信息
     * </pre>
     */
    public boolean hasResultMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string result_msg = 2;</code>
     *
     * <pre>
     *结果提示信息
     * </pre>
     */
    public String getResultMsg() {
      Object ref = resultMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result_msg = 2;</code>
     *
     * <pre>
     *结果提示信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResultMsgBytes() {
      Object ref = resultMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resultMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_FIELD_NUMBER = 3;
    private Object account_;
    /**
     * <code>optional string account = 3;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string account = 3;</code>
     */
    public String getAccount() {
      Object ref = account_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string account = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERINFO_FIELD_NUMBER = 4;
    private im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo userinfo_;
    /**
     * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
     *
     * <pre>
     *用户信息列表
     * </pre>
     */
    public boolean hasUserinfo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
     *
     * <pre>
     *用户信息列表
     * </pre>
     */
    public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo getUserinfo() {
      return userinfo_;
    }

    public static final int ACCOUNTLIST_FIELD_NUMBER = 5;
    private java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo> accountlist_;
    /**
     * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
     *
     * <pre>
     *帐号信息列表
     * </pre>
     */
    public java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo> getAccountlistList() {
      return accountlist_;
    }
    /**
     * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
     *
     * <pre>
     *帐号信息列表
     * </pre>
     */
    public java.util.List<? extends im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfoOrBuilder>
        getAccountlistOrBuilderList() {
      return accountlist_;
    }
    /**
     * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
     *
     * <pre>
     *帐号信息列表
     * </pre>
     */
    public int getAccountlistCount() {
      return accountlist_.size();
    }
    /**
     * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
     *
     * <pre>
     *帐号信息列表
     * </pre>
     */
    public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo getAccountlist(int index) {
      return accountlist_.get(index);
    }
    /**
     * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
     *
     * <pre>
     *帐号信息列表
     * </pre>
     */
    public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfoOrBuilder getAccountlistOrBuilder(
        int index) {
      return accountlist_.get(index);
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      resultCode_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode.UNKNOWN_ERROR;
      resultMsg_ = "";
      account_ = "";
      userinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.getDefaultInstance();
      accountlist_ = java.util.Collections.emptyList();
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResultMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasUserinfo()) {
        if (!getUserinfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResultMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAccountBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, userinfo_);
      }
      for (int i = 0; i < accountlist_.size(); i++) {
        output.writeMessage(5, accountlist_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResultMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAccountBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, userinfo_);
      }
      for (int i = 0; i < accountlist_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, accountlist_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code CC.Login.CCLoginRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CC.Login.CCLoginRes)
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginResOrBuilder {
      // Construct using im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode.UNKNOWN_ERROR;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        userinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000008);
        accountlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes getDefaultInstanceForType() {
        return im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes.getDefaultInstance();
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes build() {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes buildPartial() {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes result = new im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultMsg_ = resultMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userinfo_ = userinfo_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          accountlist_ = java.util.Collections.unmodifiableList(accountlist_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.accountlist_ = accountlist_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes other) {
        if (other == im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasResultMsg()) {
          bitField0_ |= 0x00000002;
          resultMsg_ = other.resultMsg_;
          
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000004;
          account_ = other.account_;
          
        }
        if (other.hasUserinfo()) {
          mergeUserinfo(other.getUserinfo());
        }
        if (!other.accountlist_.isEmpty()) {
          if (accountlist_.isEmpty()) {
            accountlist_ = other.accountlist_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureAccountlistIsMutable();
            accountlist_.addAll(other.accountlist_);
          }
          
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        if (!hasResultMsg()) {
          
          return false;
        }
        if (hasUserinfo()) {
          if (!getUserinfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (im.jizhu.com.loginmodule.protobuf.CCLogin.CCLoginRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode resultCode_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode.UNKNOWN_ERROR;
      /**
       * <code>required .CC.BaseDefine.LoginResultCode result_code = 1;</code>
       *
       * <pre>
       *结果码
       * </pre>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .CC.BaseDefine.LoginResultCode result_code = 1;</code>
       *
       * <pre>
       *结果码
       * </pre>
       */
      public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .CC.BaseDefine.LoginResultCode result_code = 1;</code>
       *
       * <pre>
       *结果码
       * </pre>
       */
      public Builder setResultCode(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        
        return this;
      }
      /**
       * <code>required .CC.BaseDefine.LoginResultCode result_code = 1;</code>
       *
       * <pre>
       *结果码
       * </pre>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.LoginResultCode.UNKNOWN_ERROR;
        
        return this;
      }

      private Object resultMsg_ = "";
      /**
       * <code>required string result_msg = 2;</code>
       *
       * <pre>
       *结果提示信息
       * </pre>
       */
      public boolean hasResultMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string result_msg = 2;</code>
       *
       * <pre>
       *结果提示信息
       * </pre>
       */
      public String getResultMsg() {
        Object ref = resultMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultMsg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string result_msg = 2;</code>
       *
       * <pre>
       *结果提示信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResultMsgBytes() {
        Object ref = resultMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resultMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result_msg = 2;</code>
       *
       * <pre>
       *结果提示信息
       * </pre>
       */
      public Builder setResultMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultMsg_ = value;
        
        return this;
      }
      /**
       * <code>required string result_msg = 2;</code>
       *
       * <pre>
       *结果提示信息
       * </pre>
       */
      public Builder clearResultMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultMsg_ = getDefaultInstance().getResultMsg();
        
        return this;
      }
      /**
       * <code>required string result_msg = 2;</code>
       *
       * <pre>
       *结果提示信息
       * </pre>
       */
      public Builder setResultMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultMsg_ = value;
        
        return this;
      }

      private Object account_ = "";
      /**
       * <code>optional string account = 3;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string account = 3;</code>
       */
      public String getAccount() {
        Object ref = account_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string account = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 3;</code>
       */
      public Builder setAccount(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        account_ = value;
        
        return this;
      }
      /**
       * <code>optional string account = 3;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        account_ = getDefaultInstance().getAccount();
        
        return this;
      }
      /**
       * <code>optional string account = 3;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        account_ = value;
        
        return this;
      }

      private im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo userinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.getDefaultInstance();
      /**
       * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
       *
       * <pre>
       *用户信息列表
       * </pre>
       */
      public boolean hasUserinfo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
       *
       * <pre>
       *用户信息列表
       * </pre>
       */
      public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo getUserinfo() {
        return userinfo_;
      }
      /**
       * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
       *
       * <pre>
       *用户信息列表
       * </pre>
       */
      public Builder setUserinfo(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        userinfo_ = value;

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
       *
       * <pre>
       *用户信息列表
       * </pre>
       */
      public Builder setUserinfo(
          im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.Builder builderForValue) {
        userinfo_ = builderForValue.build();

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
       *
       * <pre>
       *用户信息列表
       * </pre>
       */
      public Builder mergeUserinfo(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo value) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            userinfo_ != im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.getDefaultInstance()) {
          userinfo_ =
            im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.newBuilder(userinfo_).mergeFrom(value).buildPartial();
        } else {
          userinfo_ = value;
        }

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .CC.BaseDefine.UserInfo userinfo = 4;</code>
       *
       * <pre>
       *用户信息列表
       * </pre>
       */
      public Builder clearUserinfo() {
        userinfo_ = im.jizhu.com.loginmodule.protobuf.CCBaseDefine.UserInfo.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      private java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo> accountlist_ =
        java.util.Collections.emptyList();
      private void ensureAccountlistIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          accountlist_ = new java.util.ArrayList<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo>(accountlist_);
          bitField0_ |= 0x00000010;
         }
      }

      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo> getAccountlistList() {
        return java.util.Collections.unmodifiableList(accountlist_);
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public int getAccountlistCount() {
        return accountlist_.size();
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo getAccountlist(int index) {
        return accountlist_.get(index);
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder setAccountlist(
          int index, im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountlistIsMutable();
        accountlist_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder setAccountlist(
          int index, im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo.Builder builderForValue) {
        ensureAccountlistIsMutable();
        accountlist_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder addAccountlist(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountlistIsMutable();
        accountlist_.add(value);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder addAccountlist(
          int index, im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountlistIsMutable();
        accountlist_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder addAccountlist(
          im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo.Builder builderForValue) {
        ensureAccountlistIsMutable();
        accountlist_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder addAccountlist(
          int index, im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo.Builder builderForValue) {
        ensureAccountlistIsMutable();
        accountlist_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder addAllAccountlist(
          Iterable<? extends im.jizhu.com.loginmodule.protobuf.CCBaseDefine.AccountInfo> values) {
        ensureAccountlistIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accountlist_);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder clearAccountlist() {
        accountlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.AccountInfo accountlist = 5;</code>
       *
       * <pre>
       *帐号信息列表
       * </pre>
       */
      public Builder removeAccountlist(int index) {
        ensureAccountlistIsMutable();
        accountlist_.remove(index);

        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        attachData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        attachData_ = getDefaultInstance().getAttachData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CC.Login.CCLoginRes)
    }

    static {
      defaultInstance = new CCLoginRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CC.Login.CCLoginRes)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
