// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CC.Server.proto

package im.jizhu.com.loginmodule.protobuf;

public final class CCServer {
  private CCServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RouteRoleSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CC.Server.RouteRoleSet)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 master = 1;</code>
     *
     * <pre>
     *0-slave, 1-master
     * </pre>
     */
    boolean hasMaster();
    /**
     * <code>required uint32 master = 1;</code>
     *
     * <pre>
     *0-slave, 1-master
     * </pre>
     */
    int getMaster();
  }
  /**
   * Protobuf type {@code CC.Server.RouteRoleSet}
   */
  public static final class RouteRoleSet extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:CC.Server.RouteRoleSet)
      RouteRoleSetOrBuilder {
    // Use RouteRoleSet.newBuilder() to construct.
    private RouteRoleSet(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RouteRoleSet(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final RouteRoleSet defaultInstance;
    public static RouteRoleSet getDefaultInstance() {
      return defaultInstance;
    }

    public RouteRoleSet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private RouteRoleSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              master_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<RouteRoleSet> PARSER =
        new com.google.protobuf.AbstractParser<RouteRoleSet>() {
      public RouteRoleSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RouteRoleSet(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RouteRoleSet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MASTER_FIELD_NUMBER = 1;
    private int master_;
    /**
     * <code>required uint32 master = 1;</code>
     *
     * <pre>
     *0-slave, 1-master
     * </pre>
     */
    public boolean hasMaster() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 master = 1;</code>
     *
     * <pre>
     *0-slave, 1-master
     * </pre>
     */
    public int getMaster() {
      return master_;
    }

    private void initFields() {
      master_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMaster()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, master_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, master_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code CC.Server.RouteRoleSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CC.Server.RouteRoleSet)
        im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSetOrBuilder {
      // Construct using im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        master_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet getDefaultInstanceForType() {
        return im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet.getDefaultInstance();
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet build() {
        im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet buildPartial() {
        im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet result = new im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.master_ = master_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet other) {
        if (other == im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet.getDefaultInstance()) return this;
        if (other.hasMaster()) {
          setMaster(other.getMaster());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMaster()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (im.jizhu.com.loginmodule.protobuf.CCServer.RouteRoleSet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int master_ ;
      /**
       * <code>required uint32 master = 1;</code>
       *
       * <pre>
       *0-slave, 1-master
       * </pre>
       */
      public boolean hasMaster() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 master = 1;</code>
       *
       * <pre>
       *0-slave, 1-master
       * </pre>
       */
      public int getMaster() {
        return master_;
      }
      /**
       * <code>required uint32 master = 1;</code>
       *
       * <pre>
       *0-slave, 1-master
       * </pre>
       */
      public Builder setMaster(int value) {
        bitField0_ |= 0x00000001;
        master_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 master = 1;</code>
       *
       * <pre>
       *0-slave, 1-master
       * </pre>
       */
      public Builder clearMaster() {
        bitField0_ = (bitField0_ & ~0x00000001);
        master_ = 0;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CC.Server.RouteRoleSet)
    }

    static {
      defaultInstance = new RouteRoleSet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CC.Server.RouteRoleSet)
  }

  public interface RouteOnlineUserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CC.Server.RouteOnlineUserInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
     *
     * <pre>
     *route全局用户在离线状态
     * </pre>
     */
    java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus>
        getUserStatusListList();
    /**
     * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
     *
     * <pre>
     *route全局用户在离线状态
     * </pre>
     */
    im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus getUserStatusList(int index);
    /**
     * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
     *
     * <pre>
     *route全局用户在离线状态
     * </pre>
     */
    int getUserStatusListCount();
  }
  /**
   * Protobuf type {@code CC.Server.RouteOnlineUserInfo}
   */
  public static final class RouteOnlineUserInfo extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:CC.Server.RouteOnlineUserInfo)
      RouteOnlineUserInfoOrBuilder {
    // Use RouteOnlineUserInfo.newBuilder() to construct.
    private RouteOnlineUserInfo(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RouteOnlineUserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final RouteOnlineUserInfo defaultInstance;
    public static RouteOnlineUserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public RouteOnlineUserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private RouteOnlineUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                userStatusList_ = new java.util.ArrayList<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              userStatusList_.add(input.readMessage(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          userStatusList_ = java.util.Collections.unmodifiableList(userStatusList_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<RouteOnlineUserInfo> PARSER =
        new com.google.protobuf.AbstractParser<RouteOnlineUserInfo>() {
      public RouteOnlineUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RouteOnlineUserInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RouteOnlineUserInfo> getParserForType() {
      return PARSER;
    }

    public static final int USER_STATUS_LIST_FIELD_NUMBER = 1;
    private java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus> userStatusList_;
    /**
     * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
     *
     * <pre>
     *route全局用户在离线状态
     * </pre>
     */
    public java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus> getUserStatusListList() {
      return userStatusList_;
    }
    /**
     * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
     *
     * <pre>
     *route全局用户在离线状态
     * </pre>
     */
    public java.util.List<? extends im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatusOrBuilder>
        getUserStatusListOrBuilderList() {
      return userStatusList_;
    }
    /**
     * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
     *
     * <pre>
     *route全局用户在离线状态
     * </pre>
     */
    public int getUserStatusListCount() {
      return userStatusList_.size();
    }
    /**
     * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
     *
     * <pre>
     *route全局用户在离线状态
     * </pre>
     */
    public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus getUserStatusList(int index) {
      return userStatusList_.get(index);
    }
    /**
     * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
     *
     * <pre>
     *route全局用户在离线状态
     * </pre>
     */
    public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatusOrBuilder getUserStatusListOrBuilder(
        int index) {
      return userStatusList_.get(index);
    }

    private void initFields() {
      userStatusList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < userStatusList_.size(); i++) {
        output.writeMessage(1, userStatusList_.get(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < userStatusList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userStatusList_.get(i));
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code CC.Server.RouteOnlineUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CC.Server.RouteOnlineUserInfo)
        im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfoOrBuilder {
      // Construct using im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userStatusList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo getDefaultInstanceForType() {
        return im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo.getDefaultInstance();
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo build() {
        im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo buildPartial() {
        im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo result = new im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userStatusList_ = java.util.Collections.unmodifiableList(userStatusList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userStatusList_ = userStatusList_;
        return result;
      }

      public Builder mergeFrom(im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo other) {
        if (other == im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo.getDefaultInstance()) return this;
        if (!other.userStatusList_.isEmpty()) {
          if (userStatusList_.isEmpty()) {
            userStatusList_ = other.userStatusList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserStatusListIsMutable();
            userStatusList_.addAll(other.userStatusList_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (im.jizhu.com.loginmodule.protobuf.CCServer.RouteOnlineUserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus> userStatusList_ =
        java.util.Collections.emptyList();
      private void ensureUserStatusListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userStatusList_ = new java.util.ArrayList<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus>(userStatusList_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public java.util.List<im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus> getUserStatusListList() {
        return java.util.Collections.unmodifiableList(userStatusList_);
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public int getUserStatusListCount() {
        return userStatusList_.size();
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus getUserStatusList(int index) {
        return userStatusList_.get(index);
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder setUserStatusList(
          int index, im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserStatusListIsMutable();
        userStatusList_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder setUserStatusList(
          int index, im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus.Builder builderForValue) {
        ensureUserStatusListIsMutable();
        userStatusList_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder addUserStatusList(im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserStatusListIsMutable();
        userStatusList_.add(value);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder addUserStatusList(
          int index, im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserStatusListIsMutable();
        userStatusList_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder addUserStatusList(
          im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus.Builder builderForValue) {
        ensureUserStatusListIsMutable();
        userStatusList_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder addUserStatusList(
          int index, im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus.Builder builderForValue) {
        ensureUserStatusListIsMutable();
        userStatusList_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder addAllUserStatusList(
          Iterable<? extends im.jizhu.com.loginmodule.protobuf.CCBaseDefine.ServerUserStatus> values) {
        ensureUserStatusListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userStatusList_);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder clearUserStatusList() {
        userStatusList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .CC.BaseDefine.ServerUserStatus user_status_list = 1;</code>
       *
       * <pre>
       *route全局用户在离线状态
       * </pre>
       */
      public Builder removeUserStatusList(int index) {
        ensureUserStatusListIsMutable();
        userStatusList_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:CC.Server.RouteOnlineUserInfo)
    }

    static {
      defaultInstance = new RouteOnlineUserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CC.Server.RouteOnlineUserInfo)
  }

  public interface MsgServerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CC.Server.MsgServerInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string ip1 = 1;</code>
     *
     * <pre>
     *消息服务器电信IP
     * </pre>
     */
    boolean hasIp1();
    /**
     * <code>required string ip1 = 1;</code>
     *
     * <pre>
     *消息服务器电信IP
     * </pre>
     */
    String getIp1();
    /**
     * <code>required string ip1 = 1;</code>
     *
     * <pre>
     *消息服务器电信IP
     * </pre>
     */
    com.google.protobuf.ByteString
        getIp1Bytes();

    /**
     * <code>required string ip2 = 2;</code>
     *
     * <pre>
     *消息服务器联通IP
     * </pre>
     */
    boolean hasIp2();
    /**
     * <code>required string ip2 = 2;</code>
     *
     * <pre>
     *消息服务器联通IP
     * </pre>
     */
    String getIp2();
    /**
     * <code>required string ip2 = 2;</code>
     *
     * <pre>
     *消息服务器联通IP
     * </pre>
     */
    com.google.protobuf.ByteString
        getIp2Bytes();

    /**
     * <code>required uint32 port = 3;</code>
     *
     * <pre>
     *消息服务器端口
     * </pre>
     */
    boolean hasPort();
    /**
     * <code>required uint32 port = 3;</code>
     *
     * <pre>
     *消息服务器端口
     * </pre>
     */
    int getPort();

    /**
     * <code>required uint32 max_conn_cnt = 4;</code>
     *
     * <pre>
     *消息服务最大连接数
     * </pre>
     */
    boolean hasMaxConnCnt();
    /**
     * <code>required uint32 max_conn_cnt = 4;</code>
     *
     * <pre>
     *消息服务最大连接数
     * </pre>
     */
    int getMaxConnCnt();

    /**
     * <code>required uint32 cur_conn_cnt = 5;</code>
     *
     * <pre>
     *消息服务器当前连接数
     * </pre>
     */
    boolean hasCurConnCnt();
    /**
     * <code>required uint32 cur_conn_cnt = 5;</code>
     *
     * <pre>
     *消息服务器当前连接数
     * </pre>
     */
    int getCurConnCnt();

    /**
     * <code>required string host_name = 6;</code>
     *
     * <pre>
     *消息服务器域名
     * </pre>
     */
    boolean hasHostName();
    /**
     * <code>required string host_name = 6;</code>
     *
     * <pre>
     *消息服务器域名
     * </pre>
     */
    String getHostName();
    /**
     * <code>required string host_name = 6;</code>
     *
     * <pre>
     *消息服务器域名
     * </pre>
     */
    com.google.protobuf.ByteString
        getHostNameBytes();
  }
  /**
   * Protobuf type {@code CC.Server.MsgServerInfo}
   */
  public static final class MsgServerInfo extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:CC.Server.MsgServerInfo)
      MsgServerInfoOrBuilder {
    // Use MsgServerInfo.newBuilder() to construct.
    private MsgServerInfo(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgServerInfo(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final MsgServerInfo defaultInstance;
    public static MsgServerInfo getDefaultInstance() {
      return defaultInstance;
    }

    public MsgServerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private MsgServerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ip1_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ip2_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              port_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              maxConnCnt_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              curConnCnt_ = input.readUInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              hostName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<MsgServerInfo> PARSER =
        new com.google.protobuf.AbstractParser<MsgServerInfo>() {
      public MsgServerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgServerInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<MsgServerInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IP1_FIELD_NUMBER = 1;
    private Object ip1_;
    /**
     * <code>required string ip1 = 1;</code>
     *
     * <pre>
     *消息服务器电信IP
     * </pre>
     */
    public boolean hasIp1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ip1 = 1;</code>
     *
     * <pre>
     *消息服务器电信IP
     * </pre>
     */
    public String getIp1() {
      Object ref = ip1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip1 = 1;</code>
     *
     * <pre>
     *消息服务器电信IP
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIp1Bytes() {
      Object ref = ip1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP2_FIELD_NUMBER = 2;
    private Object ip2_;
    /**
     * <code>required string ip2 = 2;</code>
     *
     * <pre>
     *消息服务器联通IP
     * </pre>
     */
    public boolean hasIp2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ip2 = 2;</code>
     *
     * <pre>
     *消息服务器联通IP
     * </pre>
     */
    public String getIp2() {
      Object ref = ip2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip2 = 2;</code>
     *
     * <pre>
     *消息服务器联通IP
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIp2Bytes() {
      Object ref = ip2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>required uint32 port = 3;</code>
     *
     * <pre>
     *消息服务器端口
     * </pre>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 port = 3;</code>
     *
     * <pre>
     *消息服务器端口
     * </pre>
     */
    public int getPort() {
      return port_;
    }

    public static final int MAX_CONN_CNT_FIELD_NUMBER = 4;
    private int maxConnCnt_;
    /**
     * <code>required uint32 max_conn_cnt = 4;</code>
     *
     * <pre>
     *消息服务最大连接数
     * </pre>
     */
    public boolean hasMaxConnCnt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 max_conn_cnt = 4;</code>
     *
     * <pre>
     *消息服务最大连接数
     * </pre>
     */
    public int getMaxConnCnt() {
      return maxConnCnt_;
    }

    public static final int CUR_CONN_CNT_FIELD_NUMBER = 5;
    private int curConnCnt_;
    /**
     * <code>required uint32 cur_conn_cnt = 5;</code>
     *
     * <pre>
     *消息服务器当前连接数
     * </pre>
     */
    public boolean hasCurConnCnt() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 cur_conn_cnt = 5;</code>
     *
     * <pre>
     *消息服务器当前连接数
     * </pre>
     */
    public int getCurConnCnt() {
      return curConnCnt_;
    }

    public static final int HOST_NAME_FIELD_NUMBER = 6;
    private Object hostName_;
    /**
     * <code>required string host_name = 6;</code>
     *
     * <pre>
     *消息服务器域名
     * </pre>
     */
    public boolean hasHostName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string host_name = 6;</code>
     *
     * <pre>
     *消息服务器域名
     * </pre>
     */
    public String getHostName() {
      Object ref = hostName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hostName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host_name = 6;</code>
     *
     * <pre>
     *消息服务器域名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ip1_ = "";
      ip2_ = "";
      port_ = 0;
      maxConnCnt_ = 0;
      curConnCnt_ = 0;
      hostName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIp1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxConnCnt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurConnCnt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHostName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIp1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIp2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, port_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, maxConnCnt_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, curConnCnt_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getHostNameBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIp1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIp2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, port_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, maxConnCnt_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, curConnCnt_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getHostNameBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code CC.Server.MsgServerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CC.Server.MsgServerInfo)
        im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfoOrBuilder {
      // Construct using im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ip1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ip2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        maxConnCnt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        curConnCnt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        hostName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo getDefaultInstanceForType() {
        return im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo.getDefaultInstance();
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo build() {
        im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo buildPartial() {
        im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo result = new im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ip1_ = ip1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip2_ = ip2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maxConnCnt_ = maxConnCnt_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.curConnCnt_ = curConnCnt_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.hostName_ = hostName_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo other) {
        if (other == im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo.getDefaultInstance()) return this;
        if (other.hasIp1()) {
          bitField0_ |= 0x00000001;
          ip1_ = other.ip1_;
          
        }
        if (other.hasIp2()) {
          bitField0_ |= 0x00000002;
          ip2_ = other.ip2_;
          
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasMaxConnCnt()) {
          setMaxConnCnt(other.getMaxConnCnt());
        }
        if (other.hasCurConnCnt()) {
          setCurConnCnt(other.getCurConnCnt());
        }
        if (other.hasHostName()) {
          bitField0_ |= 0x00000020;
          hostName_ = other.hostName_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIp1()) {
          
          return false;
        }
        if (!hasIp2()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasMaxConnCnt()) {
          
          return false;
        }
        if (!hasCurConnCnt()) {
          
          return false;
        }
        if (!hasHostName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (im.jizhu.com.loginmodule.protobuf.CCServer.MsgServerInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object ip1_ = "";
      /**
       * <code>required string ip1 = 1;</code>
       *
       * <pre>
       *消息服务器电信IP
       * </pre>
       */
      public boolean hasIp1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ip1 = 1;</code>
       *
       * <pre>
       *消息服务器电信IP
       * </pre>
       */
      public String getIp1() {
        Object ref = ip1_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip1_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ip1 = 1;</code>
       *
       * <pre>
       *消息服务器电信IP
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIp1Bytes() {
        Object ref = ip1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip1 = 1;</code>
       *
       * <pre>
       *消息服务器电信IP
       * </pre>
       */
      public Builder setIp1(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip1_ = value;
        
        return this;
      }
      /**
       * <code>required string ip1 = 1;</code>
       *
       * <pre>
       *消息服务器电信IP
       * </pre>
       */
      public Builder clearIp1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip1_ = getDefaultInstance().getIp1();
        
        return this;
      }
      /**
       * <code>required string ip1 = 1;</code>
       *
       * <pre>
       *消息服务器电信IP
       * </pre>
       */
      public Builder setIp1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip1_ = value;
        
        return this;
      }

      private Object ip2_ = "";
      /**
       * <code>required string ip2 = 2;</code>
       *
       * <pre>
       *消息服务器联通IP
       * </pre>
       */
      public boolean hasIp2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ip2 = 2;</code>
       *
       * <pre>
       *消息服务器联通IP
       * </pre>
       */
      public String getIp2() {
        Object ref = ip2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip2_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ip2 = 2;</code>
       *
       * <pre>
       *消息服务器联通IP
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIp2Bytes() {
        Object ref = ip2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip2 = 2;</code>
       *
       * <pre>
       *消息服务器联通IP
       * </pre>
       */
      public Builder setIp2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip2_ = value;
        
        return this;
      }
      /**
       * <code>required string ip2 = 2;</code>
       *
       * <pre>
       *消息服务器联通IP
       * </pre>
       */
      public Builder clearIp2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip2_ = getDefaultInstance().getIp2();
        
        return this;
      }
      /**
       * <code>required string ip2 = 2;</code>
       *
       * <pre>
       *消息服务器联通IP
       * </pre>
       */
      public Builder setIp2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip2_ = value;
        
        return this;
      }

      private int port_ ;
      /**
       * <code>required uint32 port = 3;</code>
       *
       * <pre>
       *消息服务器端口
       * </pre>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 port = 3;</code>
       *
       * <pre>
       *消息服务器端口
       * </pre>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required uint32 port = 3;</code>
       *
       * <pre>
       *消息服务器端口
       * </pre>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000004;
        port_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 port = 3;</code>
       *
       * <pre>
       *消息服务器端口
       * </pre>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        
        return this;
      }

      private int maxConnCnt_ ;
      /**
       * <code>required uint32 max_conn_cnt = 4;</code>
       *
       * <pre>
       *消息服务最大连接数
       * </pre>
       */
      public boolean hasMaxConnCnt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 max_conn_cnt = 4;</code>
       *
       * <pre>
       *消息服务最大连接数
       * </pre>
       */
      public int getMaxConnCnt() {
        return maxConnCnt_;
      }
      /**
       * <code>required uint32 max_conn_cnt = 4;</code>
       *
       * <pre>
       *消息服务最大连接数
       * </pre>
       */
      public Builder setMaxConnCnt(int value) {
        bitField0_ |= 0x00000008;
        maxConnCnt_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 max_conn_cnt = 4;</code>
       *
       * <pre>
       *消息服务最大连接数
       * </pre>
       */
      public Builder clearMaxConnCnt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxConnCnt_ = 0;
        
        return this;
      }

      private int curConnCnt_ ;
      /**
       * <code>required uint32 cur_conn_cnt = 5;</code>
       *
       * <pre>
       *消息服务器当前连接数
       * </pre>
       */
      public boolean hasCurConnCnt() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 cur_conn_cnt = 5;</code>
       *
       * <pre>
       *消息服务器当前连接数
       * </pre>
       */
      public int getCurConnCnt() {
        return curConnCnt_;
      }
      /**
       * <code>required uint32 cur_conn_cnt = 5;</code>
       *
       * <pre>
       *消息服务器当前连接数
       * </pre>
       */
      public Builder setCurConnCnt(int value) {
        bitField0_ |= 0x00000010;
        curConnCnt_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 cur_conn_cnt = 5;</code>
       *
       * <pre>
       *消息服务器当前连接数
       * </pre>
       */
      public Builder clearCurConnCnt() {
        bitField0_ = (bitField0_ & ~0x00000010);
        curConnCnt_ = 0;
        
        return this;
      }

      private Object hostName_ = "";
      /**
       * <code>required string host_name = 6;</code>
       *
       * <pre>
       *消息服务器域名
       * </pre>
       */
      public boolean hasHostName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string host_name = 6;</code>
       *
       * <pre>
       *消息服务器域名
       * </pre>
       */
      public String getHostName() {
        Object ref = hostName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hostName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string host_name = 6;</code>
       *
       * <pre>
       *消息服务器域名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host_name = 6;</code>
       *
       * <pre>
       *消息服务器域名
       * </pre>
       */
      public Builder setHostName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        hostName_ = value;
        
        return this;
      }
      /**
       * <code>required string host_name = 6;</code>
       *
       * <pre>
       *消息服务器域名
       * </pre>
       */
      public Builder clearHostName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hostName_ = getDefaultInstance().getHostName();
        
        return this;
      }
      /**
       * <code>required string host_name = 6;</code>
       *
       * <pre>
       *消息服务器域名
       * </pre>
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        hostName_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CC.Server.MsgServerInfo)
    }

    static {
      defaultInstance = new MsgServerInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CC.Server.MsgServerInfo)
  }

  public interface UserCntUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CC.Server.UserCntUpdate)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 user_action = 1;</code>
     *
     * <pre>
     *用户上下线动作
     * </pre>
     */
    boolean hasUserAction();
    /**
     * <code>required uint32 user_action = 1;</code>
     *
     * <pre>
     *用户上下线动作
     * </pre>
     */
    int getUserAction();

    /**
     * <code>required string user_key = 2;</code>
     *
     * <pre>
     *用户主键
     * </pre>
     */
    boolean hasUserKey();
    /**
     * <code>required string user_key = 2;</code>
     *
     * <pre>
     *用户主键
     * </pre>
     */
    String getUserKey();
    /**
     * <code>required string user_key = 2;</code>
     *
     * <pre>
     *用户主键
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserKeyBytes();
  }
  /**
   * Protobuf type {@code CC.Server.UserCntUpdate}
   */
  public static final class UserCntUpdate extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:CC.Server.UserCntUpdate)
      UserCntUpdateOrBuilder {
    // Use UserCntUpdate.newBuilder() to construct.
    private UserCntUpdate(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserCntUpdate(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final UserCntUpdate defaultInstance;
    public static UserCntUpdate getDefaultInstance() {
      return defaultInstance;
    }

    public UserCntUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private UserCntUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userAction_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userKey_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<UserCntUpdate> PARSER =
        new com.google.protobuf.AbstractParser<UserCntUpdate>() {
      public UserCntUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserCntUpdate(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<UserCntUpdate> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ACTION_FIELD_NUMBER = 1;
    private int userAction_;
    /**
     * <code>required uint32 user_action = 1;</code>
     *
     * <pre>
     *用户上下线动作
     * </pre>
     */
    public boolean hasUserAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 user_action = 1;</code>
     *
     * <pre>
     *用户上下线动作
     * </pre>
     */
    public int getUserAction() {
      return userAction_;
    }

    public static final int USER_KEY_FIELD_NUMBER = 2;
    private Object userKey_;
    /**
     * <code>required string user_key = 2;</code>
     *
     * <pre>
     *用户主键
     * </pre>
     */
    public boolean hasUserKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string user_key = 2;</code>
     *
     * <pre>
     *用户主键
     * </pre>
     */
    public String getUserKey() {
      Object ref = userKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_key = 2;</code>
     *
     * <pre>
     *用户主键
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserKeyBytes() {
      Object ref = userKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userAction_ = 0;
      userKey_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, userAction_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserKeyBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userAction_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserKeyBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code CC.Server.UserCntUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CC.Server.UserCntUpdate)
        im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdateOrBuilder {
      // Construct using im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userAction_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate getDefaultInstanceForType() {
        return im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate.getDefaultInstance();
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate build() {
        im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate buildPartial() {
        im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate result = new im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userAction_ = userAction_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userKey_ = userKey_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate other) {
        if (other == im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate.getDefaultInstance()) return this;
        if (other.hasUserAction()) {
          setUserAction(other.getUserAction());
        }
        if (other.hasUserKey()) {
          bitField0_ |= 0x00000002;
          userKey_ = other.userKey_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserAction()) {
          
          return false;
        }
        if (!hasUserKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (im.jizhu.com.loginmodule.protobuf.CCServer.UserCntUpdate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userAction_ ;
      /**
       * <code>required uint32 user_action = 1;</code>
       *
       * <pre>
       *用户上下线动作
       * </pre>
       */
      public boolean hasUserAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 user_action = 1;</code>
       *
       * <pre>
       *用户上下线动作
       * </pre>
       */
      public int getUserAction() {
        return userAction_;
      }
      /**
       * <code>required uint32 user_action = 1;</code>
       *
       * <pre>
       *用户上下线动作
       * </pre>
       */
      public Builder setUserAction(int value) {
        bitField0_ |= 0x00000001;
        userAction_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 user_action = 1;</code>
       *
       * <pre>
       *用户上下线动作
       * </pre>
       */
      public Builder clearUserAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userAction_ = 0;
        
        return this;
      }

      private Object userKey_ = "";
      /**
       * <code>required string user_key = 2;</code>
       *
       * <pre>
       *用户主键
       * </pre>
       */
      public boolean hasUserKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string user_key = 2;</code>
       *
       * <pre>
       *用户主键
       * </pre>
       */
      public String getUserKey() {
        Object ref = userKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userKey_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string user_key = 2;</code>
       *
       * <pre>
       *用户主键
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserKeyBytes() {
        Object ref = userKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_key = 2;</code>
       *
       * <pre>
       *用户主键
       * </pre>
       */
      public Builder setUserKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userKey_ = value;
        
        return this;
      }
      /**
       * <code>required string user_key = 2;</code>
       *
       * <pre>
       *用户主键
       * </pre>
       */
      public Builder clearUserKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userKey_ = getDefaultInstance().getUserKey();
        
        return this;
      }
      /**
       * <code>required string user_key = 2;</code>
       *
       * <pre>
       *用户主键
       * </pre>
       */
      public Builder setUserKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userKey_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CC.Server.UserCntUpdate)
    }

    static {
      defaultInstance = new UserCntUpdate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CC.Server.UserCntUpdate)
  }

  public interface IMStopReceivePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CC.Server.IMStopReceivePacket)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 result = 1;</code>
     *
     * <pre>
     *结果码
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required uint32 result = 1;</code>
     *
     * <pre>
     *结果码
     * </pre>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code CC.Server.IMStopReceivePacket}
   */
  public static final class IMStopReceivePacket extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:CC.Server.IMStopReceivePacket)
      IMStopReceivePacketOrBuilder {
    // Use IMStopReceivePacket.newBuilder() to construct.
    private IMStopReceivePacket(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMStopReceivePacket(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMStopReceivePacket defaultInstance;
    public static IMStopReceivePacket getDefaultInstance() {
      return defaultInstance;
    }

    public IMStopReceivePacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMStopReceivePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMStopReceivePacket> PARSER =
        new com.google.protobuf.AbstractParser<IMStopReceivePacket>() {
      public IMStopReceivePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMStopReceivePacket(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMStopReceivePacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required uint32 result = 1;</code>
     *
     * <pre>
     *结果码
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 result = 1;</code>
     *
     * <pre>
     *结果码
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, result_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, result_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code CC.Server.IMStopReceivePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CC.Server.IMStopReceivePacket)
        im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacketOrBuilder {
      // Construct using im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket getDefaultInstanceForType() {
        return im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket.getDefaultInstance();
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket build() {
        im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket buildPartial() {
        im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket result = new im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket other) {
        if (other == im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (im.jizhu.com.loginmodule.protobuf.CCServer.IMStopReceivePacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>required uint32 result = 1;</code>
       *
       * <pre>
       *结果码
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 result = 1;</code>
       *
       * <pre>
       *结果码
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required uint32 result = 1;</code>
       *
       * <pre>
       *结果码
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 result = 1;</code>
       *
       * <pre>
       *结果码
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CC.Server.IMStopReceivePacket)
    }

    static {
      defaultInstance = new IMStopReceivePacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CC.Server.IMStopReceivePacket)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
