//
// Created by it031 on 2017/12/21.
//

#include "im_jizhu_com_loginmodule_jni_JNIUtils.h"
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class im_jizhu_com_loginmodule_jni_JNIUtils */

#ifndef _Included_im_jizhu_com_loginmodule_jni_JNIUtils
#define _Included_im_jizhu_com_loginmodule_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/**
 * 上边的引用标签一定是.h的文件名家后缀，方法名一定要和.h文件中的方法名称一样
 */
JNIEXPORT jstring JNICALL Java_im_jizhu_com_loginmodule_jni_JNIUtils_getString
        (JNIEnv *env, jobject obj) {
    return (*env)->NewStringUTF(env, "这是我测试的jni");
}

#ifdef __cplusplus
}
#endif
#endif