/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class im_jizhu_com_loginmodule_Security */

#ifndef _Included_im_jizhu_com_loginmodule_Security
#define _Included_im_jizhu_com_loginmodule_Security
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     im_jizhu_com_loginmodule_Security
 * Method:    DecryptMsg
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_jizhu_com_loginmodule_Security_DecryptMsg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     im_jizhu_com_loginmodule_Security
 * Method:    EncryptMsg
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_jizhu_com_loginmodule_Security_EncryptMsg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     im_jizhu_com_loginmodule_Security
 * Method:    EncryptPass
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_jizhu_com_loginmodule_Security_EncryptPass
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
