/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class im_jizhu_com_loginmodule_jni_JNIUtils */

#ifndef _Included_im_jizhu_com_loginmodule_jni_JNIUtils
#define _Included_im_jizhu_com_loginmodule_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     im_jizhu_com_loginmodule_jni_JNIUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_im_jizhu_com_loginmodule_jni_JNIUtils_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
