/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpptest_jizhu_com_cpptest_Cpp */

#ifndef _Included_cpptest_jizhu_com_cpptest_Cpp
#define _Included_cpptest_jizhu_com_cpptest_Cpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpptest_jizhu_com_cpptest_Cpp
 * Method:    sayhello
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cpptest_jizhu_com_cpptest_Cpp_sayhello
  (JNIEnv *, jobject, jint);

/*
 * Class:     cpptest_jizhu_com_cpptest_Cpp
 * Method:    returnString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cpptest_jizhu_com_cpptest_Cpp_returnString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
