package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table appinfo.
 */
public class AppEntity {

    /** Not-null value. */
    private String appID;
    private String iconUrl;
    private String zipUrl;
    private Double appVen;
    private String appName;
    private Boolean isDownloaded;
    private String localSplash;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AppEntity() {
    }

    public AppEntity(String appID) {
        this.appID = appID;
    }

    public AppEntity(String appID, String iconUrl, String zipUrl, Double appVen, String appName, Boolean isDownloaded, String localSplash) {
        this.appID = appID;
        this.iconUrl = iconUrl;
        this.zipUrl = zipUrl;
        this.appVen = appVen;
        this.appName = appName;
        this.isDownloaded = isDownloaded;
        this.localSplash = localSplash;
    }

    /** Not-null value. */
    public String getAppID() {
        return appID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppID(String appID) {
        this.appID = appID;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getZipUrl() {
        return zipUrl;
    }

    public void setZipUrl(String zipUrl) {
        this.zipUrl = zipUrl;
    }

    public Double getAppVen() {
        return appVen;
    }

    public void setAppVen(Double appVen) {
        this.appVen = appVen;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Boolean getIsDownloaded() {
        return isDownloaded;
    }

    public void setIsDownloaded(Boolean isDownloaded) {
        this.isDownloaded = isDownloaded;
    }

    public String getLocalSplash() {
        return localSplash;
    }

    public void setLocalSplash(String localSplash) {
        this.localSplash = localSplash;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
