package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CollectionInfo.
 */
public class CollectionEntity {

    private Long id;
    private int type;
    private String name;
    private String content;
    private String avatar;
    private String time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CollectionEntity() {
    }

    public CollectionEntity(Long id) {
        this.id = id;
    }

    public CollectionEntity(Long id, int type, String name, String content, String avatar, String time) {
        this.id = id;
        this.type = type;
        this.name = name;
        this.content = content;
        this.avatar = avatar;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
