package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ContactInfo.
 */
public class ContactEntity {

    private Long id;
    private int contactId;
    private int type;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String realName;
    /** Not-null value. */
    private String avatar;

    private String phone;
    private String email;
    private int departmentId;
    private String signInfo;
    private String telephone;
    private String pinyinName;
    private int status;
    private int typeId;
    private String sapVkorg;
    private String oanum;
    private int created;

    private int userStatus;
    private int isOnline;

    private int gender;

    //2017_9_18新增字段添加组织架构（部门、公司。成员）的上级id
    private int parentDepartId;
    //部门人员数量
    private int subDepartCount;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ContactEntity() {
    }

    public ContactEntity(Long id) {
        this.id = id;
    }

    public ContactEntity(Long id, int contactId, int type, String name, String realName, String avatar,int userStatus,int isOnline,int gender) {
        this.id = id;
        this.contactId = contactId;
        this.type = type;
        this.name = name;
        this.realName = realName;
        this.avatar = avatar;
        this.userStatus = userStatus;
        this.isOnline = isOnline;
        this.gender = gender;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getContactId() {
        return contactId;
    }

    public void setContactId(int contactId) {
        this.contactId = contactId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getRealName() {
        return realName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /** Not-null value. */
    public String getAvatar() {
        return avatar;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public int getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(int userStatus) {
        this.userStatus = userStatus;
    }

    public int getIsOnline() {
        return isOnline;
    }

    public void setIsOnline(int isOnline) {
        this.isOnline = isOnline;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }

    public String getSignInfo() {
        return signInfo;
    }

    public void setSignInfo(String signInfo) {
        this.signInfo = signInfo;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getPinyinName() {
        return pinyinName;
    }

    public void setPinyinName(String pinyinName) {
        this.pinyinName = pinyinName;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getTypeId() {
        return typeId;
    }

    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }

    public String getSapVkorg() {
        return sapVkorg;
    }

    public void setSapVkorg(String sapVkorg) {
        this.sapVkorg = sapVkorg;
    }

    public String getOanum() {
        return oanum;
    }

    public void setOanum(String oanum) {
        this.oanum = oanum;
    }

    public int getCreated() {
        return created;
    }

    public void setCreated(int created) {
        this.created = created;
    }

    public int getParentDepartId() {
        return parentDepartId;
    }

    public void setParentDepartId(int parentDepartId) {
        this.parentDepartId = parentDepartId;
    }

    public int getSubDepartCount() {
        return subDepartCount;
    }

    public void setSubDepartCount(int subDepartCount) {
        this.subDepartCount = subDepartCount;
    }
// KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
