package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table Depart.
 */
public class DepartEntity {

    private Long depart_id;
    /** Not-null value. */
    private String guid;
    private int container_id;
    private int id;
    /** Not-null value. */
    private String name;
    private int pid;
    private int sort;
    /** Not-null value. */
    private String depart_text1;
    /** Not-null value. */
    private String depart_text2;
    /** Not-null value. */
    private String depart_text3;
    /** Not-null value. */
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DepartEntity() {
    }

    public DepartEntity(Long depart_id, String guid) {
        this.depart_id = depart_id;
        this.guid = guid;
    }

    public DepartEntity(Long depart_id, String guid, int container_id, int id, String name, int pid, int sort, String depart_text1, String depart_text2, String depart_text3, String status) {
        this.depart_id = depart_id;
        this.guid = guid;
        this.container_id = container_id;
        this.id = id;
        this.name = name;
        this.pid = pid;
        this.sort = sort;
        this.depart_text1 = depart_text1;
        this.depart_text2 = depart_text2;
        this.depart_text3 = depart_text3;
        this.status = status;
    }

    public Long getDepart_id() {
        return depart_id;
    }

    public void setDepart_id(Long depart_id) {
        this.depart_id = depart_id;
    }

    /** Not-null value. */
    public String getGuid() {
        return guid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    public int getContainer_id() {
        return container_id;
    }

    public void setContainer_id(int container_id) {
        this.container_id = container_id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getPid() {
        return pid;
    }

    public void setPid(int pid) {
        this.pid = pid;
    }

    public int getSort() {
        return sort;
    }

    public void setSort(int sort) {
        this.sort = sort;
    }

    /** Not-null value. */
    public String getDepart_text1() {
        return depart_text1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDepart_text1(String depart_text1) {
        this.depart_text1 = depart_text1;
    }

    /** Not-null value. */
    public String getDepart_text2() {
        return depart_text2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDepart_text2(String depart_text2) {
        this.depart_text2 = depart_text2;
    }

    /** Not-null value. */
    public String getDepart_text3() {
        return depart_text3;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDepart_text3(String depart_text3) {
        this.depart_text3 = depart_text3;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
