package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table UserInfo.
 */
public class UserInfoEntity {

    private Long userinfo_id;
    /** Not-null value. */
    private String guid;
    private int id;
    private int container_id;
    private int name;
    /** Not-null value. */
    private String avatar;
    private int attach;
    /** Not-null value. */
    private String depart;
    /** Not-null value. */
    private String uservalue_list;
    /** Not-null value. */
    private String userinfo_text1;
    /** Not-null value. */
    private String userinfo_text2;
    /** Not-null value. */
    private String userinfo_text3;
    /** Not-null value. */
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserInfoEntity() {
    }

    public UserInfoEntity(Long userinfo_id) {
        this.userinfo_id = userinfo_id;
    }

    public UserInfoEntity(Long userinfo_id, String guid, int id, int container_id, int name, String avatar, int attach, String depart, String uservalue_list, String userinfo_text1, String userinfo_text2, String userinfo_text3, String status) {
        this.userinfo_id = userinfo_id;
        this.guid = guid;
        this.id = id;
        this.container_id = container_id;
        this.name = name;
        this.avatar = avatar;
        this.attach = attach;
        this.depart = depart;
        this.uservalue_list = uservalue_list;
        this.userinfo_text1 = userinfo_text1;
        this.userinfo_text2 = userinfo_text2;
        this.userinfo_text3 = userinfo_text3;
        this.status = status;
    }

    public Long getUserinfo_id() {
        return userinfo_id;
    }

    public void setUserinfo_id(Long userinfo_id) {
        this.userinfo_id = userinfo_id;
    }

    /** Not-null value. */
    public String getGuid() {
        return guid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getContainer_id() {
        return container_id;
    }

    public void setContainer_id(int container_id) {
        this.container_id = container_id;
    }

    public int getName() {
        return name;
    }

    public void setName(int name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getAvatar() {
        return avatar;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public int getAttach() {
        return attach;
    }

    public void setAttach(int attach) {
        this.attach = attach;
    }

    /** Not-null value. */
    public String getDepart() {
        return depart;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDepart(String depart) {
        this.depart = depart;
    }

    /** Not-null value. */
    public String getUservalue_list() {
        return uservalue_list;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUservalue_list(String uservalue_list) {
        this.uservalue_list = uservalue_list;
    }

    /** Not-null value. */
    public String getUserinfo_text1() {
        return userinfo_text1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserinfo_text1(String userinfo_text1) {
        this.userinfo_text1 = userinfo_text1;
    }

    /** Not-null value. */
    public String getUserinfo_text2() {
        return userinfo_text2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserinfo_text2(String userinfo_text2) {
        this.userinfo_text2 = userinfo_text2;
    }

    /** Not-null value. */
    public String getUserinfo_text3() {
        return userinfo_text3;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserinfo_text3(String userinfo_text3) {
        this.userinfo_text3 = userinfo_text3;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
