package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table UserValue.
 */
public class UserValueEntity {

    private Long uservalue_id;
    /** Not-null value. */
    private String guid;
    private int key;
    /** Not-null value. */
    private String value;
    /** Not-null value. */
    private String uservalue_text1;
    /** Not-null value. */
    private String uservalue_text2;
    /** Not-null value. */
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserValueEntity() {
    }

    public UserValueEntity(Long uservalue_id, String guid) {
        this.uservalue_id = uservalue_id;
        this.guid = guid;
    }

    public UserValueEntity(Long uservalue_id, String guid, int key, String value, String uservalue_text1, String uservalue_text2, String status) {
        this.uservalue_id = uservalue_id;
        this.guid = guid;
        this.key = key;
        this.value = value;
        this.uservalue_text1 = uservalue_text1;
        this.uservalue_text2 = uservalue_text2;
        this.status = status;
    }

    public Long getUservalue_id() {
        return uservalue_id;
    }

    public void setUservalue_id(Long uservalue_id) {
        this.uservalue_id = uservalue_id;
    }

    /** Not-null value. */
    public String getGuid() {
        return guid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    public int getKey() {
        return key;
    }

    public void setKey(int key) {
        this.key = key;
    }

    /** Not-null value. */
    public String getValue() {
        return value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValue(String value) {
        this.value = value;
    }

    /** Not-null value. */
    public String getUservalue_text1() {
        return uservalue_text1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUservalue_text1(String uservalue_text1) {
        this.uservalue_text1 = uservalue_text1;
    }

    /** Not-null value. */
    public String getUservalue_text2() {
        return uservalue_text2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUservalue_text2(String uservalue_text2) {
        this.uservalue_text2 = uservalue_text2;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
