package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table UserStatusInfo.
 */
public class UserStatusEntity {

    private Long id;
    private int userStatus;
    private int userId;
    private  int isOnline;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserStatusEntity() {
    }

    public UserStatusEntity(Long id) {
        this.id = id;
    }

    public UserStatusEntity(Long id,int userId,int userStatus,int isOnline) {

        this.id = id;
        this.userId = userId;
        this.userStatus = userStatus;
        this.isOnline = isOnline;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(int userStatus) {
        this.userStatus = userStatus;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getIsOnline() {
        return isOnline;
    }

    public void setIsOnline(int isOnline) {
        this.isOnline = isOnline;
    }

// KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
