package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table UserName.
 */
public class UserNameEntity {

    private Long username_id;
    private int id;
    /** Not-null value. */
    private String value;
    /** Not-null value. */
    private String english_name;
    /** Not-null value. */
    private String nick;
    /** Not-null value. */
    private String word_name;
    /** Not-null value. */
    private String number_name;
    /** Not-null value. */
    private String net_name;
    /** Not-null value. */
    private String pinying_name;
    /** Not-null value. */
    private String pinying_first_name;
    /** Not-null value. */
    private String pinying_nick;
    /** Not-null value. */
    private String username_text1;
    /** Not-null value. */
    private String username_text2;
    /** Not-null value. */
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserNameEntity() {
    }

    public UserNameEntity(Long username_id, int id) {
        this.username_id = username_id;
        this.id = id;
    }

    public UserNameEntity(Long username_id, int id, String value, String english_name, String nick, String word_name, String number_name, String net_name, String pinying_name, String pinying_first_name, String pinying_nick, String username_text1, String username_text2, String status) {
        this.username_id = username_id;
        this.id = id;
        this.value = value;
        this.english_name = english_name;
        this.nick = nick;
        this.word_name = word_name;
        this.number_name = number_name;
        this.net_name = net_name;
        this.pinying_name = pinying_name;
        this.pinying_first_name = pinying_first_name;
        this.pinying_nick = pinying_nick;
        this.username_text1 = username_text1;
        this.username_text2 = username_text2;
        this.status = status;
    }

    public Long getUsername_id() {
        return username_id;
    }

    public void setUsername_id(Long username_id) {
        this.username_id = username_id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getValue() {
        return value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValue(String value) {
        this.value = value;
    }

    /** Not-null value. */
    public String getEnglish_name() {
        return english_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEnglish_name(String english_name) {
        this.english_name = english_name;
    }

    /** Not-null value. */
    public String getNick() {
        return nick;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /** Not-null value. */
    public String getWord_name() {
        return word_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWord_name(String word_name) {
        this.word_name = word_name;
    }

    /** Not-null value. */
    public String getNumber_name() {
        return number_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNumber_name(String number_name) {
        this.number_name = number_name;
    }

    /** Not-null value. */
    public String getNet_name() {
        return net_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNet_name(String net_name) {
        this.net_name = net_name;
    }

    /** Not-null value. */
    public String getPinying_name() {
        return pinying_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPinying_name(String pinying_name) {
        this.pinying_name = pinying_name;
    }

    /** Not-null value. */
    public String getPinying_first_name() {
        return pinying_first_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPinying_first_name(String pinying_first_name) {
        this.pinying_first_name = pinying_first_name;
    }

    /** Not-null value. */
    public String getPinying_nick() {
        return pinying_nick;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPinying_nick(String pinying_nick) {
        this.pinying_nick = pinying_nick;
    }

    /** Not-null value. */
    public String getUsername_text1() {
        return username_text1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername_text1(String username_text1) {
        this.username_text1 = username_text1;
    }

    /** Not-null value. */
    public String getUsername_text2() {
        return username_text2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername_text2(String username_text2) {
        this.username_text2 = username_text2;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
