package im.jizhu.com.loginmodule.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table UserKey.
 */
public class UserKeyEntity {

    private Long userkey_id;
    private Integer id;
    private int type;
    /** Not-null value. */
    private String key;
    /** Not-null value. */
    private String defualt_value;
    /** Not-null value. */
    private String desc;
    /** Not-null value. */
    private String userkey_text1;
    /** Not-null value. */
    private String userkey_text2;
    /** Not-null value. */
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserKeyEntity() {
    }

    public UserKeyEntity(Long userkey_id, Integer id) {
        this.userkey_id = userkey_id;
        this.id = id;
    }

    public UserKeyEntity(Long userkey_id, Integer id, int type, String key, String defualt_value, String desc, String userkey_text1, String userkey_text2, String status) {
        this.userkey_id = userkey_id;
        this.id = id;
        this.type = type;
        this.key = key;
        this.defualt_value = defualt_value;
        this.desc = desc;
        this.userkey_text1 = userkey_text1;
        this.userkey_text2 = userkey_text2;
        this.status = status;
    }

    public Long getUserkey_id() {
        return userkey_id;
    }

    public void setUserkey_id(Long userkey_id) {
        this.userkey_id = userkey_id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    /** Not-null value. */
    public String getDefualt_value() {
        return defualt_value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDefualt_value(String defualt_value) {
        this.defualt_value = defualt_value;
    }

    /** Not-null value. */
    public String getDesc() {
        return desc;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /** Not-null value. */
    public String getUserkey_text1() {
        return userkey_text1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserkey_text1(String userkey_text1) {
        this.userkey_text1 = userkey_text1;
    }

    /** Not-null value. */
    public String getUserkey_text2() {
        return userkey_text2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserkey_text2(String userkey_text2) {
        this.userkey_text2 = userkey_text2;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
